#include <cstdio>
#include <cstring>
#include <cstdlib>
#include "NDfield.h"

// ============================================================
// Serial NDfield writer
//
// This reproduces the binary format generated by
// DisPerSE's Save_NDfield().
//
// ============================================================

int WriteNDfield(const char *filename, NDfield *field)
{
    int i;

    char tag[16];
    char dummy[160];

    FILE *f;


    // --------------------------------------------------------
    // Initialize temporary arrays
    // --------------------------------------------------------

    memset(tag, 0, sizeof(tag));
    memset(dummy, 0, sizeof(dummy));

    strcpy(tag, NDFIELD_TAG);


    // --------------------------------------------------------
    // Open binary file
    //
    // IMPORTANT:
    // Use "wb", not "w".
    // --------------------------------------------------------

    f = fopen(filename, "wb");

    if (f == NULL)
    {
        perror("fopen");
        return -1;
    }


    // ========================================================
    // TAG RECORD
    // ========================================================

    i = 16;

    // Record length
    fwrite(&i, sizeof(int), 1, f);

    // "NDFIELD"
    fwrite(tag, sizeof(char), 16, f);

    // Record length
    fwrite(&i, sizeof(int), 1, f);


    // ========================================================
    // HEADER RECORD
    // ========================================================

    //
    // Calculate header payload size.
    //
    // This is exactly the expression used by DisPerSE:
    //
    // sizeof(int)*(NDFIELD_MAX_DIMS+3)
    // + sizeof(double)*(2*NDFIELD_MAX_DIMS)
    // + (160+80)
    //

    i =
        sizeof(int) *
        (NDFIELD_MAX_DIMS + 3)
        +
        sizeof(double) *
        (2 * NDFIELD_MAX_DIMS)
        +
        (160 + 80);


    // Header record length

    fwrite(&i, sizeof(int), 1, f);


    // --------------------------------------------------------
    // comment
    // --------------------------------------------------------

    fwrite(field->comment,
           sizeof(char),
           80,
           f);


    // --------------------------------------------------------
    // ndims
    // --------------------------------------------------------

    fwrite(&field->ndims,
           sizeof(int),
           1,
           f);


    // --------------------------------------------------------
    // dims
    // --------------------------------------------------------

    fwrite(field->dims,
           sizeof(int),
           field->ndims,
           f);


    // Remaining dimensions are zero-filled.

    if (field->ndims < NDFIELD_MAX_DIMS)
    {
        fwrite(dummy,
               sizeof(int),
               NDFIELD_MAX_DIMS - field->ndims,
               f);
    }


    // --------------------------------------------------------
    // fdims_index
    // --------------------------------------------------------

    fwrite(&field->fdims_index,
           sizeof(int),
           1,
           f);


    // --------------------------------------------------------
    // datatype
    // --------------------------------------------------------

    fwrite(&field->datatype,
           sizeof(int),
           1,
           f);


    // --------------------------------------------------------
    // x0
    // --------------------------------------------------------

    fwrite(field->x0,
           sizeof(double),
           field->ndims,
           f);


    if (field->ndims < NDFIELD_MAX_DIMS)
    {
        fwrite(dummy,
               sizeof(double),
               NDFIELD_MAX_DIMS - field->ndims,
               f);
    }


    // --------------------------------------------------------
    // delta
    // --------------------------------------------------------

    fwrite(field->delta,
           sizeof(double),
           field->ndims,
           f);


    if (field->ndims < NDFIELD_MAX_DIMS)
    {
        fwrite(dummy,
               sizeof(double),
               NDFIELD_MAX_DIMS - field->ndims,
               f);
    }


    // --------------------------------------------------------
    // 160-byte dummy extension
    // --------------------------------------------------------

    fwrite(field->dummy,
           sizeof(char),
           160,
           f);


    // --------------------------------------------------------
    // End of header record
    // --------------------------------------------------------

    fwrite(&i,
           sizeof(int),
           1,
           f);


    // ========================================================
    // DATA RECORD
    // ========================================================

    i =
        field->nval *
        sizeof_NDfield(field->datatype);


    // Data record length

    fwrite(&i,
           sizeof(int),
           1,
           f);


    // Actual data

    fwrite(field->val,
           sizeof_NDfield(field->datatype),
           field->nval,
           f);


    // Data record length again

    fwrite(&i,
           sizeof(int),
           1,
           f);


    // ========================================================
    // Done
    // ========================================================

    fclose(f);

    return 0;
}

// ============================================================
// Write NDfield as a legacy binary VTK STRUCTURED_POINTS file
// ============================================================
//
// Assumptions:
//   - field is a regular grid
//   - field.ndims == 3
//   - field.fdims_index == 0
//   - field.datatype == ND_DOUBLE
//   - field.val contains double values
//
// The NDfield convention is:
//
//     x0    = bounding-box origin
//     delta = bounding-box size
//
// Therefore VTK grid spacing is:
//
//     dx = delta[0] / dims[0]
//     dy = delta[1] / dims[1]
//     dz = delta[2] / dims[2]
//
// ============================================================

void WriteNDfieldToVTK(const char* filename,
                       const NDfield& field,
                       const char* scalar_name = "density")
{
    // --------------------------------------------------------
    // Check that this is a 3D regular grid
    // --------------------------------------------------------

    if (field.ndims != 3)
    {
        std::cerr << "ERROR: VTK writer requires ndims = 3.\n";
        std::exit(1);
    }

    if (field.fdims_index != 0)
    {
        std::cerr << "ERROR: VTK writer requires a regular grid "
                  << "(fdims_index = 0).\n";
        std::exit(1);
    }

    if (field.datatype != ND_DOUBLE)
    {
        std::cerr << "ERROR: VTK writer currently requires "
                  << "ND_DOUBLE data.\n";
        std::exit(1);
    }

    if (field.val == nullptr)
    {
        std::cerr << "ERROR: field.val is null.\n";
        std::exit(1);
    }


    // --------------------------------------------------------
    // Grid dimensions
    // --------------------------------------------------------

    const int nx = field.dims[0];
    const int ny = field.dims[1];
    const int nz = field.dims[2];


    // --------------------------------------------------------
    // Physical origin
    // --------------------------------------------------------

    const double x0 = field.x0[0];
    const double y0 = field.x0[1];
    const double z0 = field.x0[2];


    // --------------------------------------------------------
    // NDfield delta is the bounding-box size.
    //
    // Convert it to grid spacing for VTK.
    // --------------------------------------------------------

    const double dx =
        field.delta[0] / static_cast<double>(nx);

    const double dy =
        field.delta[1] / static_cast<double>(ny);

    const double dz =
        field.delta[2] / static_cast<double>(nz);


    // --------------------------------------------------------
    // Number of values
    // --------------------------------------------------------

    const long nval =
        static_cast<long>(nx) *
        static_cast<long>(ny) *
        static_cast<long>(nz);


    // --------------------------------------------------------
    // Access field data
    // --------------------------------------------------------

    const double* data =
        static_cast<const double*>(field.val);


    // --------------------------------------------------------
    // Open binary VTK file
    // --------------------------------------------------------

    std::ofstream out(filename, std::ios::binary);

    if (!out)
    {
        std::cerr << "ERROR: Could not open VTK file "
                  << filename << " for writing.\n";
        std::exit(1);
    }


    // ========================================================
    // VTK header
    // ========================================================

    out << "# vtk DataFile Version 3.0\n";

    out << "NDfield density field\n";

    out << "BINARY\n";

    out << "DATASET STRUCTURED_POINTS\n";


    // --------------------------------------------------------
    // Grid dimensions
    // --------------------------------------------------------

    out << "DIMENSIONS "
        << nx << " "
        << ny << " "
        << nz << "\n";


    // --------------------------------------------------------
    // Origin
    // --------------------------------------------------------

    out << std::setprecision(17);

    out << "ORIGIN "
        << x0 << " "
        << y0 << " "
        << z0 << "\n";


    // --------------------------------------------------------
    // Grid spacing
    // --------------------------------------------------------

    out << "SPACING "
        << dx << " "
        << dy << " "
        << dz << "\n";


    // --------------------------------------------------------
    // Number of points
    //
    // For STRUCTURED_POINTS, the scalar array is associated
    // with points.
    // --------------------------------------------------------

    out << "POINT_DATA "
        << nval << "\n";


    // --------------------------------------------------------
    // Scalar field
    // --------------------------------------------------------

    out << "SCALARS "
        << scalar_name
        << " double 1\n";

    out << "LOOKUP_TABLE default\n";


    // ========================================================
    // Binary data
    //
    // VTK legacy binary format requires BIG-ENDIAN data.
    //
    // Most modern machines are LITTLE-ENDIAN, so swap the
    // bytes before writing.
    // ========================================================

    for (long i = 0; i < nval; ++i)
    {
        unsigned char bytes[sizeof(double)];

        // Copy double into byte array
        std::memcpy(bytes,
                    &data[i],
                    sizeof(double));

        // Reverse byte order:
        // little endian -> big endian

        for (std::size_t b = 0; b < sizeof(double) / 2; ++b)
        {
            std::swap(bytes[b],
                      bytes[sizeof(double) - 1 - b]);
        }

        out.write(
            reinterpret_cast<const char*>(bytes),
            sizeof(double)
        );
    }


    // --------------------------------------------------------
    // Check write status
    // --------------------------------------------------------

    if (!out)
    {
        std::cerr << "ERROR: Error while writing VTK file "
                  << filename << "\n";
        std::exit(1);
    }

    out.close();

    std::cout << "Successfully wrote VTK file: "
              << filename << "\n";
}

int sizeof_NDfield(int type)
{
    switch (type)
    {
        case ND_CHAR:
        case ND_UCHAR:
            return 1;

        case ND_SHORT:
        case ND_USHORT:
            return 2;

        case ND_INT:
        case ND_UINT:
            return 4;

        case ND_LONG:
        case ND_ULONG:
            return 8;

        case ND_FLOAT:
            return 4;

        case ND_DOUBLE:
            return 8;

        default:
            return 0;
    }
}
